### ISSUE TITLE
Validatie geeft

### ISSUE THREAD

**Issue by Theo-denBlanken** [kgeurts/Modaal-2.0#1]
Je hebt feedback gekregen van **Theo-denBlanken**
op:
```c
<!DOCTYPE html> <html> <head> <title>Album Covers 2.0</title> <link rel="stylesheet" type="text/css" href="modaal.css"> </head> 
```

URL: https://github.com/kgeurts/Modaal-2.0/blob/master/index.html

Feedback: 1 error[](http://www.studiozoetekauw.nl/codereview-in-het-onderwijs/ '#cr:{"sha":"7d8b4fdf7b0682eb957cd40c8ca4cee8937b3faa","path":"index.html","reviewer":"Theo-denBlanken"}')

**Comment by kgeurts** [comment]
Error's eruit gehaald.
